name: Playwright Tests

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
    
jobs:

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Upload HTML report as Artifact
      uses: actions/upload-artifact@v2
      if: always()
      with: 
        name: pw-reports
        path: pw-reports/
        
  storeReports:
    name: Store reports
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      id: download
    - name: Publish to external repo
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        external_repository: fearlessly-dev/playwright.reports
        publish_branch: gh-pages
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ${{steps.download.outputs.download-path}}
        keep_files: true
        user_name: "github-actions[bot]"
        user_email: "github-actions[bot]@users.noreply.github.com"
    
